//%attributes = {"invisible":true}
ARRAY PICTURE:C279(<>_PROGRESSICON;0)
ARRAY LONGINT:C221(<>_PROGRESSID;0)
ARRAY TEXT:C222(<>_PROGRESSMESSAGE;0)
ARRAY TEXT:C222(<>_PROGRESSONSTOP;0)
ARRAY TEXT:C222(<>_PROGRESSTITLE;0)
ARRAY BOOLEAN:C223(<>_PROGRESSUPDATED;0)
ARRAY REAL:C219(<>_PROGRESSVALUE;0)

ARRAY BOOLEAN:C223(<>_ProgressCancelAllow;0)
ARRAY BOOLEAN:C223(<>_ProgressCanceled;0)
ARRAY TEXT:C222(<>_ProgressCancelButtonText;0)
