name: Release
on: 
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    permissions:
      contents: write # for asset upload
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
      - name: BuildAndPackage
        uses: 4d/build4d-action@main
        with:
          actions: "build,pack,archive"
      - name: Upload
        run: |
          gh release upload ${{github.event.release.tag_name}} "build/4D-Progress.zip"
